### ISSUE TITLE
Compliance tests that randomize AFTOperation order or implicit replace

### ISSUE THREAD

**Issue by liulk** [openconfig/gribigo#144]
There are some compliance tests that randomize the AFTOperation order like this one:

https://github.com/openconfig/gribigo/blob/1a335e84e0162cd388ff9ac1e019cbb35c09713d/compliance/compliance.go#L537

Or implicit replace:

https://github.com/openconfig/gribigo/blob/1a335e84e0162cd388ff9ac1e019cbb35c09713d/compliance/compliance.go#L763

The only specification I could find regarding the order is this:

```
message ModifyRequest {
  // A group of requests to add/modify/remove a single AFT entry.
  //
  // A gRIBI server :
  //  * Should process AFTOperations per the received order.
  ...
  repeated AFTOperation operation = 1;
}
```

https://github.com/openconfig/gribi/blob/2aaba323cde619765adcb25aae1855b962a4f667/v1/proto/service/gribi.proto#L62

By the way, each AFTOperation also has an `id` field, and the wording in `ModifyRequest` suggests that the operation ordering should be as "received" rather than ordered by this `id`.

I vaguely recall that there are some assumptions that vendors have made:

  * Forward referencing is not allowed, i.e. NH needs to be defined before NHG, and NHG defined before IPv4.
  * Implicit replace is not allowed, i.e. if NH exists, add the same NH should fail.

Can we formalized these assumptions as rules in gribi.proto and remove the compliance tests that violate these rules?

**Comment by nandanarista** [comment]
- I think we should remove `AddIPv4EntryRandom` since forward references amongst AFTs aren't allowed. This is something we should update the protobuf to be more explicit
There's some text about `missing references` but that's not sufficient.
```
   // FAILED is used to indicate that operation that was provided
    // cannot be programmed, for example, due to invalid message
    // contents, or missing references.
```    

- Operations are processed by a server  in the order they are in the `operation` in a `ModifyRequest` (received order). The `id` just needs to be unique enough such that the client can tie the response to the request; the fact that most, if not all clients, may choose to make it monotonically increasing is a client implementation choice.

- `ImplicitReplaceNH` can likely stay. Maybe some vendors choose not to support replace for NH if the client - server deployment doesn't need it.

**Comment by liulk** [comment]
I think there are two issues:

- gRIBI spec allows `ADD` to be interpreted as a `REPLACE` if the entry already exists.
- Although gRIBI spec doesn't mandate this, `REPLACE` typically expects "make before break" semantics such that traffic should not be dropped during the operation.

A corollary is that `ADD` without `REPLACE` is vastly simpler. I suspect many vendors will likewise find `REPLACE` with "make before break" difficult to implement.

I think from the compliance test perspective, `ADD` without `REPLACE` is easier to cover as well. To make things easier for everyone, maybe we should update the gRIBI spec to disallow `REPLACE` both as a standalone op and as part of `ADD`?

@xw-g @dplore for input.

**Comment by xw-g** [comment]
* I agree that we probably should remove [AddIPv4EntryRandom](https://github.com/openconfig/gribigo/blob/1a335e84e0162cd388ff9ac1e019cbb35c09713d/compliance/compliance.go#L520), because it sets the wrong expectation that the device SHOULD buffer/cache all operations for referencing/dependency check.  @liulk do you want to open a PR? 

* Yes, we do have gaps, or vague parts, in the proto definition, we plan to work on a formal spec (in the format of public branch/PRs). 

* @robshakir @nflath maybe can help comment on `ADD` v.s. `REPLACE` use cases

**Comment by xw-g** [comment]
To further clarify, I meant
* we probably want to keep the semantics of implicit replace in `ADD`, otherwise it might introduce extra complexity in controller logic. 
* whether we should keep `REPLACE` op, maybe @robshakir and @nflath can help comment.

**Comment by nflath** [comment]
REPLACE is unused in the controller right now, because we want the behaviour of implicit replace for simplicity (and more intent-based rather than having to track entries)

**Comment by liulk** [comment]
From chat, it sounds like standalone `REPLACE` might be error prone to use correctly by a gRIBI client because it now has to keep track of whether an entry already exists or not. If we all agree, then it makes sense to remove it from the protocol.

On the other hand, implicit replace in `ADD` is preferred by the client. They are still using implicit replace for NHG and IPv4Entry, even though they currently have to do delete+add for NH as a workaround. If that's the case, then I think we can keep it in gribi.proto but add clarification about the "make before break" semantics of the implicit replace.

As far as compliance test goes, I would like to see test coverage to be representative of client use cases, and that all tests pass on all vendors. But maybe adding a command line flag to skip the implicit replace case is an acceptable compromise.

**Comment by nflath** [comment]
We aren't delete+adding NHs as a workaround, it's just how we do the Gribi ops.  If they supported in-place NH replace via ADD we still wouldn't use it.

**Comment by liulk** [comment]
It sounded like your controller is not doing delete+add nor implicit replace on NH at all, but let me try to paraphrase it differently and let me know if this is closer to what you meant: the controller happens to be doing delete+add for NH and not implicit replacing NH, but that's how the controller works rather than as a workaround. And your controller still needs implicit replace for NHG and IPv4Entry. Is this correct?

And would you agree that other controllers may still want to implicit-replace NH, and we should keep it in the gRIBI spec for `ADD`?

**Comment by liulk** [comment]
About whether some of the test cases should be removed, while working on this I realized that there is already some selection mechanism built into the compliance test runner, so I'm just adding a new marker.

If we're not changing gribi.proto, then this should be all we need to do for this issue. Thanks for all the comments and feedback.
